const Types = {
  REQUEST_API_DATA: "@user/REQUEST_API_DATA",
  SET_API_DATA: "@user/SET_API_DATA",
  UI_POST_REQUEST: "@user/UI_POST_REQUEST",
  CREATE_POST_SUCCESS: "@user/CREATE_POST_SUCCESS",
  DELETE_POST: "@user/DELETE_POST",
  EDIT_POST: "@user/EDIT_POST",
  ON_SUCCESS_DELETE_POST: "@user/ON_SUCCESS_DELETE_POST",
};

export default Types;
